apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-secrets
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: ea2cec6e-2ece-4917-bc32-18e9e7c535d5
    keyvaultName: postgres-db-credentials
    cloudName: ""
    objects: |
      array:
        - |
          objectName: DB-HOST
          objectType: secret
        - |
          objectName: DB-NAME
          objectType: secret
        - |
          objectName: DB-PASSWORD
          objectType: secret
        - |
          objectName: DB-PORT
          objectType: secret
        - |
          objectName: DB-USER
          objectType: secret
        - |
          objectName: SECRET-KEY
          objectType: secret
    tenantId: 72ca12ad-1c5b-400e-a56e-de2f46920121
  secretObjects:
    - secretName: db-credentials
      type: Opaque
      data:
        - key: db_host
          objectName: DB-HOST
        - key: db_name
          objectName: DB-NAME
        - key: db_password
          objectName: DB-PASSWORD
        - key: db_port
          objectName: DB-PORT
        - key: db_user
          objectName: DB-USER
        - key: secret_key
          objectName: SECRET-KEY
