apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-secrets
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: d08bdaf4-4c08-4d1b-8591-1549300fb39c
    keyvaultName: postgres-db-credentials
    cloudName: ""
    objects: |
      array:
        - |
          objectName: DB-PASSWORD
          objectType: secret
        - |
          objectName: SECRET-KEY
          objectType: secret
    tenantId: eb9b34bc-dedb-4667-9285-7868247187e6
  secretObjects:
    - secretName: db-credentials
      type: Opaque
      data:
        - key: db_password
          objectName: DB-PASSWORD
        - key: secret_key
          objectName: SECRET-KEY
